### ISSUE TITLE
error: STACK_GLOBAL requires str

### ISSUE THREAD

**Issue by ryali93** [Orion-AI-Lab/FLOGA#1]
https://github.com/Orion-AI-Lab/FLOGA/blob/baf412aae4c06189de7a1fe0b8bcc1ffead751fc/dataset_utils.py#L144

If anyone has this issue
  File "/home/*************/python3.8/site-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: STACK_GLOBAL requires str

Update this line
```
loaded_sample[sample_info] = torch.from_numpy(np.load(sample[sample_info]))
```

in the other conditions, it is similar

**Comment by paren8esis** [comment]
Thank you for opening this issue!

Did you export the dataset in numpy format instead of pytorch tensors?

**Comment by paren8esis** [comment]
FYI, I updated `dataset_utils.py` to also support numpy array data. I reckon that this was the error you encountered, so I resolve this issue.
